//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class id_type
    {
        public int id { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public Nullable<int> id_type1 { get; set; }
    
        public virtual id id1 { get; set; }
    }
}
